### ISSUE TITLE
No new commits

### ISSUE THREAD

**Issue by madrinathapa** [airavata-courses/haphulwa#3]
Hello Harsha,

I don't see any new commits as we discussed earlier. 

Thank you,
Madrina Thapa

**Comment by harsha161992** [comment]
Hi Madrina,

I am updating the code on my local machine.

I should be done by tonight :)

*Thanks & Regards,*
*Harsha Phulwani*

**Comment by harsha161992** [comment]
Hey,

I just pushed the updated code. You can check now :)

*Thanks & Regards,*
*Harsha Phulwani*
