### ISSUE TITLE
Assignment 1: Comments

### ISSUE THREAD

**Issue by Ameya05** [airavata-courses/haphulwa#4]
Good job on the microservices, I saw these are already dockerized and were easy to setup.
However, at the moment your static index.html file is not hosted on any server and is calling the micro-services directly.

```
$("#java").click(function() {
                $.ajax({
                    url: "http://localhost:8085",
                    success: function(data) {
                        document.getElementById('hello_msg').innerHTML = data;
                    },
                    error: function(xhr, ajaxOptions, thrownError) {
                        document.getElementById('hello_msg').innerHTML = thrownError;
                    }
                });
            });
```

Please implement an API Server which acts as a gateway to all the micro-services. The UI should only interact with the API Server.
API Server is responsible for performing the necessary micro-service invocations and returning output to the UI. You could refer to the [lecture slides](http://courses.airavata.org/slides/SICE-Fall17-B649-Assignment-1.pdf) for a better understanding of what I am suggesting.

**Comment by harsha161992** [comment]
Okay Ameya, thanks! I tried implementing the API gateway. It works fine on my local machine but is giving me issues when I run it on the server. I've posted the issue in the discussion forum of our class. Can you please have a look at it?

**Comment by Ameya05** [comment]
Please let me know if the Assignment 1 is ready for re-grading.

**Comment by harsha161992** [comment]
Hey, yes it is ready.
Thanks!

**Comment by Ameya05** [comment]
Working as expected. Closing this issue!
