### ISSUE TITLE
Assignment 2 Review

### ISSUE THREAD

**Issue by Ameya05** [airavata-courses/haphulwa#5]
Hi Harsha,

The Docker and Rabbitmq part looks good to me.
Can you give a bit of detail on how the Jenkins setup is at the moment? Updating the Architecture diagram would help too.

**Comment by harsha161992** [comment]
Hi Ameya,

I updated the wiki and wrote about the Jenkins configuration I have.

**Comment by Ameya05** [comment]
Great thanks.
