### ISSUE TITLE
Application not accessible

### ISSUE THREAD

**Issue by eldhomathulla** [airavata-courses/haphulwa#6]
Unable to access the deployed application.

**Comment by harsha161992** [comment]
Hey, I am able to access it.
Are you on the right URL- http://129.114.17.184:5000/ 
Attaching a screenshot of the expected result.
![screenshot_20170926_114027](https://user-images.githubusercontent.com/17470082/30869762-0311ceae-a2b0-11e7-9486-21d08a7b012e.png)

**Comment by eldhomathulla** [comment]
Double checked again application working fine.
